### ISSUE TITLE
新手，项目本地运行需要配置什么啊，4000端口 不能获得数据。node npm 装了 还需要配置什么么

### ISSUE THREAD

**Issue by yegouhuo** [xxxgitone/vue-node-pastime#6]

**Comment by yegouhuo** [comment]
# clone项目
git clone git@github.com:xxxgitone/vue-node-pastime.git

cd vue-node-pastime

# install dependencies
npm install

# 还原数据，为了方便展示，我将数据库上传到了项目中，文件名为vnpastime
# --host 数据库服务
# -d 数据库名
# 最后面是备份文件的路径,如果不在该目录下记得填写绝对路径
mongorestore --host 127.0.0.1:27017 -d vnpastime ./vnpastime/

# 启动mongodb服务
mongo

# 启动后台服务
node app.js

# 再启动前台
npm run dev

# build for production with minification
npm run build
我是按照这个流程在  gitbash中进行的  浏览器是谷歌

**Comment by yegouhuo** [comment]
请问各位大神，你们是怎么把项目运行起来的。

**Comment by yegouhuo** [comment]
npm run dev

> vn-pastime@1.0.0 dev F:\vue-node-pastime
> node build/dev-server.js

[HPM] Proxy created: /api  ->  http://localhost:4000
[HPM] Proxy created: /auth  ->  http://localhost:4000
> Starting dev server...
**events.js:183
     

-###   throw er; // Unhandled 'error' event**

      ^

Error: listen EADDRINUSE :::8080
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at Server.setupListenHandle [as _listen2] (net.js:1355:14)
    at listenInCluster (net.js:1396:12)
    at Server.listen (net.js:1480:7)
    at Function.listen (F:\vue-node-pastime\node_modules\express\lib\application.js:618:24)
    at Object.<anonymous> (F:\vue-node-pastime\build\dev-server.js:84:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vn-pastime@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! **_Failed at the vn-pastime@1.0.0 dev script._**
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\nodejs\node_cache\_logs\2018-06-21T13_15_13_065Z-debug.log

**Comment by yegouhuo** [comment]
端口占用了  清理了4000  8080         的进程id 就可以啦

**Comment by yegouhuo** [comment]
从异常信息可以看出是 本地的8088端口被占用

解决方法： 
1.更改webpack-dev-server启动时的端口

2.结束占用端口的进程

netstat -aon|findstr “端口号”
taskkill /pid “占用端口的PID” /f
