### ISSUE TITLE
执行node app.js的时候项目报错

### ISSUE THREAD

**Issue by DickLicha** [xxxgitone/vue-node-pastime#9]
具体报错内容是说找不到 mongo_conf模块，这个问题该如何解决呢
`Error: Cannot find module './mongo_conf'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (F:\vue-node-pastime\app.js:12:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3`

**Comment by lumos102** [comment]
app.js文件同级新建一个`mongo_conf.js`文件<br>
文件内容是：
`module.exports = {
  mongodb: 'mongodb://localhost:27017/vnpastime'
}`
